insert into genres (name_genre)
values ('Detective'),
       ('Drama'),
       ('Love history'),
       ('Historical novel'),
       ('Сomedy'),
       ('Love story'),
       ('Novella'),
       ('Poetry'),
       ('Adventure novel'),
       ('Gothic novel'),
       ('Dramaturgy'),
       ('Mystical novel'),
       ('Non-fiction'),
       ('Psychological novel'),
       ('Satire'),
       ('Fairy tale'),
       ('Tragedy'),
       ('Fantastic'),
       ('Fantasy novel');